# Generated by Django 2.2.3 on 2019-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('result', models.TextField()),
                ('time_taken', models.CharField(max_length=255)),
            ],
        ),
    ]
