# Generated by Django 2.2.3 on 2019-09-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacci',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fibonacci',
            name='result',
            field=models.TextField(),
        ),
    ]
